version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - NickReisenauer
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - NickReisenauer
